### ISSUE TITLE
question: always return SWAGGER_RESPONSE_VALIDATION_FAILED

### ISSUE THREAD

**Issue by emj365** [carlansley/swagger2-koa#23]
thank you create this project

in https://github.com/emj365/test-swagger2-koa

I just set up very simple example but 

```
→ curl localhost:3000/ping
{"code":"SWAGGER_RESPONSE_VALIDATION_FAILED","errors":[{"expected":{},"where":"response"}]}
```

could you help was wrong with it? I spent few hours on this.

**Comment by carlansley** [comment]
The issue is that we don't support an undefined basePath.  If you set basePath to '/api' or something I'm sure /api/ping will work.  I'll fix it in the next version that defines a default of '' for the basePath.

**Comment by emj365** [comment]
@carlansley it still doesn't, please check https://github.com/emj365/test-swagger2-koa/pull/1

**Comment by carlansley** [comment]
The master of your repo works.  The new branch you created has a bug - the router.get should be passed '/ping', not '/api/ping'.  The base path (/api) is automatically prepended by the router.

**Comment by emj365** [comment]
Thank you take time to check my codes. the point is I don't know swaggerRouter auto add the prefix `/api` to the router.

**Comment by ryantzor** [comment]
I still have this issue have you had any other reports of it? Sometimes I can get it to return that it's "Missing string" in "Body" or something to that effect, but it still doesn't tell you what the name of the param you're missing.

`basePath: /
paths:
  /helloWorld:
    get:
      operationId: serviceTemplate
      summary: Hello World
      tags:
        - serviceTemplate
      description: Hello world route for service template
      produces:
        - application/json
      parameters:         
        - in: query
          name: "id"
          type: "string"
          required: true
          description: "Id of customer to update"
        - in: body
          name: "payload"
          schema:
            type: "object"`
            
          without those in the body or query string the api returns 
`{
  "code": "SWAGGER_REQUEST_VALIDATION_FAILED",
  "errors": [
    {
      "expected": {
        "type": "string"
      },
      "where": "query"
    }
  ]
}`

**Comment by carlansley** [comment]
I would read this as its missing an "id" string as a the query parameter

**Comment by ryantzor** [comment]
@carlansley Yeah I see what you're saying. Should swagger2-koa be showing the param name in the error though if it's not present in the query string?

I updated the spec to the following with two query string params and it outputs this error:
ERROR:
```json
{
  "code": "SWAGGER_REQUEST_VALIDATION_FAILED",
  "errors": [
    {
      "expected": {
        "type": "string"
      },
      "where": "query"
    },
    {
      "expected": {
        "type": "string"
      },
      "where": "query"
    }
  ]
}
```
SPEC:
```yaml
paths:
  /helloWorld:
    get:
      operationId: serviceTemplate
      summary: Hello World
      tags:
        - serviceTemplate
      description: Hello world route for service template
      produces:
        - application/json
      parameters:         
        - in: query
          name: id
          type: "string"
          required: true
        - in: query
          name: test
          type: "string"
          required: true
          description: "Id of customer to update"
        - in: body
          name: "payload"
          schema:
            type: "object"
```
