### ISSUE TITLE
Response models validate but do not appear in api docs

### ISSUE THREAD

**Issue by eseyfried** [carlansley/swagger2-koa#48]
Given the following syntax from api.yaml, request validation works fine. However, the response model shows up as "string".
If I remove "shema" from the put responses object, then the api docs show the model correctly but then response validation fails. How can I achieve both?

```
/tenant/{tenantId}:
  put:
      ...
      responses:
            200:
              description: "OK"
              schema:
                $ref: '#/responses/Tenant'
```

```
responses:
  "Tenant":
    schema:
      $ref: '#/definitions/Tenant'
```

```
definitions:
  Tenant:
    type: "object"
    properties:
      status: 
        type: "string"
      data:
        type: "object"
        properties:
          id:
            type: "integer"
            format: "int64"
          firstName:
            type: "string"
          lastName:
            type: "string"
          email:
            type: "string"
          createdAt:
            type: "string"
          updatedAt:
            type: "string"
          deletedAt:
            type: "string"
```
